name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx (optional, but recommended for advanced builds)
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: sirgeon
        password: ${{ secrets.DCKR_HUB }}

    - name: Build the Docker image
      run: |
        docker build . --file landing-page.Dockerfile --tag sirgeon/dockrelix-landing-page:latest

    - name: Push the Docker image to Docker Hub
      run: |
        docker push sirgeon/dockrelix-landing-page:latest
